### ISSUE TITLE
× Unhandled Rejection (TypeError): Cannot read property 'buyTokens' of undefined

### ISSUE THREAD

**Issue by besiwims** [parv3213/GargToken#2]
Unhandled Rejection (TypeError): Cannot read property 'buyTokens' of undefined
buyTokens
c:/Users/Ottilia/GargToken-ICO-Sale/src/components/App.jsx:79
  76 | 
  77 | const buyTokens = async (tokens) => {
  78 | 	setLoading(true);
> 79 | 	await tokenSale.methods
     | ^  80 | 		.buyTokens(tokens)
  81 | 		.send({ value: window.web3.utils.toWei(String(tokens * tokenPrice), "ether"), from: account })
  82 | 		.on("transactionHash", (hash) => {
View compiled
handleSubmit
c:/Users/Ottilia/GargToken-ICO-Sale/src/components/Card.jsx:12
   9 | 
  10 | const handleSubmit = async (event) => {
  11 | 	event.preventDefault();
> 12 | 	await props.buyTokens(tokens);
     | ^  13 | };
  14 | 
  15 | return (
View compiled
▶ 22 stack frames were collapsed.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.

**Comment by parv3213** [comment]
Hi @besiwims, 
this could be due to some missing dependencies. I have added some essential dependencies required for this project. Please clone the latest code. 
Also, there is a point to note here, as this project was meant for local development, there are few additional steps that you will need to perform in order to make this work. 
Steps required:
1. Have an instance of Ganache running at port 8545. 
2. You will have to redeploy the contracts. For this, type following in the root directory
`truffle migrate --reset`
2. Make sure your browser Metamask network is set to "LocalHost 8545".

**Comment by besiwims** [comment]
Thanks. Its running now but on port 9545 via Custom RPC
